@startuml
'https://plantuml.com/activity-diagram-beta

start
:Переход пользователя в корзину;
:Чтение id выбранных товаров из localStorage;
repeat
  :Ввод контактных данных пользователя в форму заявки заказа;
repeat while (Введенные данные валидны?)
:Формирование запроса о заказе для отправки;
:Сохранение запроса в бд;
stop

@enduml
