@startuml
'https://plantuml.com/activity-diagram-beta

start
:Переход в каталог товаров;
:Чтение списка товаров;
:Вывод товаров пользователю;
:Выбор пользователем категорий сортировки;
if (Категории для сортировки выбраны?) is (yes) then
  :Получение списка категорий для сортировки;
  :Сортирока списка товаров по полученным категориям;
  :Обновление отображаемой информации;
else (no)
  :Оставить список товаров неизменным;
endif
:Просмотр каталога;
stop
@enduml
