@startuml
'https://plantuml.com/activity-diagram-beta

start
:Переход в каталог товаров;
:Чтение списка товаров;
:Вывод товаров пользователю;
:Ввод пользователем названия искомого товара;
:Считывание введенного названия;
:Поиск товаров в соответствии с введенным значением;
if (Есть совпадения?) is (yes) then
  :Вывод списка совпадений;
else (no)
  :Вывод сообщения, что совпадений нет;
endif
:Обновление выводимой информации;
:Просмотр каталога;
stop
@enduml
