@startuml
'https://plantuml.com/activity-diagram-beta

start
:Переход в каталог товаров;
:Чтение списка товаров;
:Вывод товаров пользователю;
:Нажатие на карточку товара пользователем;
:Чтение id товара;
:Поиск товара в списке товаров;
:Формирование карточки товара из полученных данных;
:Переход на карточку товара;
if (Добавить товар в корзину?) is (yes) then
  :Добавление id товара в localStorage;
endif

stop
@enduml
