@startuml
'https://plantuml.com/activity-diagram-beta
|Пользователь|
start
:Переход пользователя в корзину;
|Web ресурс|
:Чтение id выбранных товаров из localStorage;
|Пользователь|
repeat
  :Ввод контактных данных пользователя в форму заявки заказа;
repeat while (Введенные данные валидны?)
|Web ресурс|
:Формирование запроса о заказе для отправки;
:Сохранение запроса в бд;
|Пользователь|
stop

@enduml
