@startuml
'https://plantuml.com/activity-diagram-beta

|Пользователь|
start
:Переход в каталог товаров;
|Web ресурс|
:Чтение списка товаров;
:Вывод товаров пользователю;
|Пользователь|
:Выбор пользователем категорий сортировки;
|Web ресурс|
if (Категории для сортировки выбраны?) is (yes) then
  :Получение списка категорий для сортировки;
  :Сортирока списка товаров по полученным категориям;
  :Обновление отображаемой информации;
else (no)
  :Оставить список товаров неизменным;
endif
|Пользователь|
:Просмотр каталога;
stop
@enduml
