@startuml
'https://plantuml.com/activity-diagram-beta

start
:Переход в каталог товаров;
:Чтение списка товаров;
:Вывод товаров пользователю;
:Выбор пользователем типа сортировки;
if (Сортировать по возрастанию?) is (yes) then
  :Сортирока списка товаров по возрастанию;
elseif (Сортировать по убыванию) then
  :Сортирока списка товаров по возрастанию;
else (no)
  :Оставить список товаров неизменным;
endif
:Обновление отображаемой информации;
:Просмотр каталога;
stop
@enduml
