@startuml
'https://plantuml.com/activity-diagram-beta

|Пользователь|
start
:Переход в каталог товаров;
|Web ресурс|
:Чтение списка товаров;
:Вывод товаров пользователю;
|Пользователь|
:Ввод пользователем названия искомого товара;
|Web ресурс|
:Считывание введенного названия;
:Поиск товаров в соответствии с введенным значением;
if (Есть совпадения?) is (yes) then
  :Вывод списка совпадений;
else (no)
  :Вывод сообщения, что совпадений нет;
endif
:Обновление выводимой информации;
|Пользователь|
:Просмотр каталога;
stop
@enduml
