@startuml
'https://plantuml.com/activity-diagram-beta

|Пользователь|
start
:Переход в каталог товаров;
|Web ресурс|
:Чтение списка товаров;
:Вывод товаров пользователю;
|Пользователь|
:Нажатие на карточку товара пользователем;
|Web ресурс|
:Чтение id товара;
:Поиск товара в списке товаров;
:Формирование карточки товара из полученных данных;
:Переход на карточку товара;
|Пользователь|
:Просмотр карточки товара;
if (Добавить товар в корзину?) is (yes) then
  |Web ресурс|
  :Добавление id товара в localStorage;
endif
|Пользователь|
stop
@enduml
