@startuml
'https://plantuml.com/activity-diagram-beta

|Пользователь|
start
:Переход в каталог товаров;
|Web ресурс|
:Чтение списка товаров;
:Вывод товаров пользователю;
|Пользователь|
:Выбор пользователем типа сортировки;
|Web ресурс|
if (Сортировать по возрастанию?) is (yes) then
  :Сортирока списка товаров по возрастанию;
elseif (Сортировать по убыванию) then
  :Сортирока списка товаров по возрастанию;
else (no)
  :Оставить список товаров неизменным;
endif
:Обновление отображаемой информации;
|Пользователь|
:Просмотр каталога;
stop
@enduml
