@startuml
'https://plantuml.com/activity-diagram-beta

|Пользователь|
start
:Переход продавца на страницу управления товарами;
|Web ресурс|
:Чтение списка товаров;
|Пользователь|
:Редактирование продавцом свойств товаров;
if (Сохранить изменения?) is (yes) then
  |Web ресурс|
  :Обновление данных в бд;
else (no)
  |Web ресурс|
  :Сброс введенных настроек;
|Пользователь|
endif
stop

@enduml
