@startuml
'https://plantuml.com/activity-diagram-beta

start
:Переход продавца на страницу управления заказами;
:Чтение списка заказов;
:Отображение списка текущих заказов;
if (Редактировать заказ?) is (yes) then
  :Внесение изменений в заказ;
  :Считывание изменений;
  :Применение изменений к списку заказов отображаемой информации;
elseif (Удалить заказ?) then
  :Чтение id удаленного заказа;
  :Удаление заказа из списка закаов отображаемой информации;
else (no)
endif
:Обновление отображаемой информации;
if (Сохранить изменения?) is (yes) then
  :Обновление данных в бд;
else (no)
  :Сброс введенных настроек;
endif
stop

@enduml
