@startuml
'https://plantuml.com/activity-diagram-beta

|Пользователь|
start
:Переход продавца на страницу импортирования данных;
:Ввод пользователем источника данных (файл xml));
|Web ресурс|
:Чтение полученного файла;
if (Полученный файл валиден?) is (yes) then
  :Считывание данных из файла;
  :Обновление отображаемой информации;
  |Пользователь|
  if (Сохранить изменеия?) is (yes) then
    |Web ресурс|
    :Применение изменений в бд;
  else (no)
    |Web ресурс|
    :Отмена изменений;
  endif
else (no)
  :Сообщение о невалидности файла;
endif
|Пользователь|
stop

@enduml
