@startuml
'https://plantuml.com/activity-diagram-beta

start
:Переход продавца на страницу авторизации;

repeat
  :Заполнение продавцом формы авторизации;
repeat while (Введенные данные валидны?)
:Получение продавцом токена;
:Перенаправление на главную страницу админ панели;

stop

@enduml
