@startuml
'https://plantuml.com/activity-diagram-beta

start
:Переход продавца на страницу управления товарами;
:Чтение списка товаров;
:Редактирование продавцом свойств товаров;
if (Сохранить изменения?) is (yes) then
  :Обновление данных в бд;
else (no)
  :Сброс введенных настроек;
endif
stop

@enduml
