@startuml
'https://plantuml.com/activity-diagram-beta

|Пользователь|
start
:Переход продавца на страницу авторизации;

repeat
  :Заполнение продавцом формы авторизации;
repeat while (Введенные данные валидны?)
|Web ресурс|
:Получение продавцом токена;
:Перенаправление на главную страницу админ панели;
|Пользователь|
stop

@enduml
