@startuml
'https://plantuml.com/activity-diagram-beta

start
:Переход продавца на страницу импортирования данных;
:Ввод пользователем источника данных (файл xml));
:Чтение полученного файла;
if (Полученный файл валиден?) is (yes) then
  :Считывание данных из файла;
  :Обновление отображаемой информации;
  if (Сохранить изменеия?) is (yes) then
    :Применение изменений в бд;
  else (no)
    :Отмена изменений;
  endif
else (no)
  :Сообщение о невалидности файла;
endif

stop

@enduml
